// 50 Hindi-film classics from the 70s, 80s and 90s — the office chill queue.
//
// Every entry was checked against YouTube for three things: the video exists,
// it is public, and it allows embedding. Playback streams from YouTube through
// the IFrame player, so nothing is stored or redistributed here.
//
// Uploads do disappear. `npm run check:playlist` re-tests all 50, and
// `node scripts/resolve-playlist.mjs "Title|Film|Year|Singers"` finds a
// replacement and prints an entry to paste in here.
export const PLAYLIST = [
  {
    id: '-sTS4XozNnY',
    title: 'Yeh Shaam Mastani',
    film: 'Kati Patang',
    year: 1970,
    singers: 'Kishore Kumar',
    seconds: 270,
  },
  {
    id: 'VrIDPJyEqvs',
    title: 'Zindagi Ek Safar Hai Suhana',
    film: 'Andaz',
    year: 1971,
    singers: 'Kishore Kumar',
    seconds: 151,
  },
  {
    id: 'llEK3DZSCWU',
    title: 'Piya Tu Ab To Aaja',
    film: 'Caravan',
    year: 1971,
    singers: 'Asha Bhosle',
    seconds: 263,
  },
  {
    id: 'GUn3P5QyLRY',
    title: 'Dum Maro Dum',
    film: 'Hare Rama Hare Krishna',
    year: 1971,
    singers: 'Asha Bhosle',
    seconds: 162,
  },
  {
    id: 'qWRw17tQ8UA',
    title: 'O Mere Dil Ke Chain',
    film: 'Mere Jeevan Saathi',
    year: 1972,
    singers: 'Kishore Kumar',
    seconds: 268,
  },
  {
    id: 'J5GbDHQnUJg',
    title: 'Gum Hai Kisi Ke Pyar Mein',
    film: 'Rampur Ka Lakshman',
    year: 1972,
    singers: 'Kishore Kumar Lata Mangeshkar',
    seconds: 274,
  },
  {
    id: '_R7Po4Wpbj8',
    title: 'Chura Liya Hai Tumne Jo Dil Ko',
    film: 'Yaadon Ki Baaraat',
    year: 1973,
    singers: 'Asha Bhosle Mohammed Rafi',
    seconds: 277,
  },
  {
    id: '0HqHruwzusM',
    title: 'Ek Ajnabee Haseena Se',
    film: 'Ajnabee',
    year: 1974,
    singers: 'Kishore Kumar',
    seconds: 267,
  },
  {
    id: '-xcna3K80tA',
    title: 'Tere Bina Zindagi Se Koi',
    film: 'Aandhi',
    year: 1975,
    singers: 'Kishore Kumar Lata Mangeshkar',
    seconds: 355,
  },
  {
    id: '1T8G_d5o5Gs',
    title: 'Yeh Dosti Hum Nahi Todenge',
    film: 'Sholay',
    year: 1975,
    singers: 'Kishore Kumar Manna Dey',
    seconds: 378,
  },
  {
    id: 'ByAbV-MKDgs',
    title: 'Mehbooba Mehbooba',
    film: 'Sholay',
    year: 1975,
    singers: 'R D Burman',
    seconds: 231,
  },
  {
    id: '87DchBGxqV8',
    title: 'Kabhi Kabhie Mere Dil Mein',
    film: 'Kabhi Kabhie',
    year: 1976,
    singers: 'Mukesh',
    seconds: 300,
  },
  {
    id: 'hS3PQnHd9Cg',
    title: 'Parda Hai Parda',
    film: 'Amar Akbar Anthony',
    year: 1977,
    singers: 'Mohammed Rafi',
    seconds: 394,
  },
  {
    id: 'W6dKaCV-mJQ',
    title: 'Kya Hua Tera Wada',
    film: 'Hum Kisise Kum Naheen',
    year: 1977,
    singers: 'Mohammed Rafi',
    seconds: 265,
  },
  {
    id: 'zgcW44Id114',
    title: 'Bachna Ae Haseeno',
    film: 'Hum Kisise Kum Naheen',
    year: 1977,
    singers: 'Kishore Kumar',
    seconds: 407,
  },
  {
    id: 'Q3EisUe0CAM',
    title: 'Khaike Paan Banaras Wala',
    film: 'Don',
    year: 1978,
    singers: 'Kishore Kumar',
    seconds: 253,
  },
  {
    id: 'MrEfdm_evUs',
    title: 'Aap Ki Ankhon Mein Kuch',
    film: 'Ghar',
    year: 1978,
    singers: 'Kishore Kumar Lata Mangeshkar',
    seconds: 310,
  },
  {
    id: 'HBAuj9GghZ4',
    title: 'O Saathi Re Tere Bina',
    film: 'Muqaddar Ka Sikandar',
    year: 1978,
    singers: 'Kishore Kumar',
    seconds: 322,
  },
  {
    id: 'IVaOvVL2IBU',
    title: 'Hum Bewafa Hargiz Na The',
    film: 'Shalimar',
    year: 1978,
    singers: 'Kishore Kumar',
    seconds: 242,
  },
  {
    id: 'KRHif-zSlbM',
    title: 'Rimjhim Gire Sawan',
    film: 'Manzil',
    year: 1979,
    singers: 'Kishore Kumar',
    seconds: 243,
  },
  {
    id: 'I_iIY81069o',
    title: 'Om Shanti Om',
    film: 'Karz',
    year: 1980,
    singers: 'Kishore Kumar',
    seconds: 323,
  },
  {
    id: '1kO8Iopt0Jg',
    title: 'Aap Jaisa Koi Meri Zindagi Mein Aaye',
    film: 'Qurbani',
    year: 1980,
    singers: 'Nazia Hassan',
    seconds: 227,
  },
  {
    id: 'yl8R4gvVMkg',
    title: 'Yaad Aa Raha Hai Tera Pyar',
    film: 'Disco Dancer',
    year: 1982,
    singers: 'Bappi Lahiri',
    seconds: 382,
  },
  {
    id: 'fRSLPx0HSvw',
    title: 'Jimmy Jimmy Aaja Aaja',
    film: 'Disco Dancer',
    year: 1982,
    singers: 'Parvati Khan',
    seconds: 185,
  },
  {
    id: '8A30PWazxMU',
    title: 'Ae Zindagi Gale Laga Le',
    film: 'Sadma',
    year: 1983,
    singers: 'Suresh Wadkar',
    seconds: 328,
  },
  {
    id: 'lMSbXOYtDI4',
    title: 'Sun Sahiba Sun',
    film: 'Ram Teri Ganga Maili',
    year: 1985,
    singers: 'Lata Mangeshkar',
    seconds: 337,
  },
  {
    id: 'IgKdXLfxgQQ',
    title: 'Hawa Hawai',
    film: 'Mr India',
    year: 1987,
    singers: 'Kavita Krishnamurthy',
    seconds: 419,
  },
  {
    id: 'FEvBiayarlc',
    title: 'Papa Kehte Hain Bada Naam Karega',
    film: 'Qayamat Se Qayamat Tak',
    year: 1988,
    singers: 'Udit Narayan',
    seconds: 367,
  },
  {
    id: 'ipGUPjNVqXk',
    title: 'Ae Mere Humsafar',
    film: 'Qayamat Se Qayamat Tak',
    year: 1988,
    singers: 'Udit Narayan Alka Yagnik',
    seconds: 356,
  },
  {
    id: 'JzFemLoFkN4',
    title: 'Ek Do Teen',
    film: 'Tezaab',
    year: 1988,
    singers: 'Alka Yagnik',
    seconds: 458,
  },
  {
    id: '6Pq4tBP3VV8',
    title: 'Dil Deewana Bin Sajna Ke',
    film: 'Maine Pyar Kiya',
    year: 1989,
    singers: 'Lata Mangeshkar',
    seconds: 319,
  },
  {
    id: 'kKC1hAcPoI4',
    title: 'My Name Is Lakhan',
    film: 'Ram Lakhan',
    year: 1989,
    singers: 'Nitin Mukesh Mohammed Aziz',
    seconds: 421,
  },
  {
    id: 'bEXtVh9gcAg',
    title: 'Nazar Ke Samne',
    film: 'Aashiqui',
    year: 1990,
    singers: 'Kumar Sanu Anuradha Paudwal',
    seconds: 333,
  },
  {
    id: 'N-aIg_YkMaQ',
    title: 'Dekha Hai Pehli Baar',
    film: 'Saajan',
    year: 1991,
    singers: 'S P Balasubrahmanyam Alka Yagnik',
    seconds: 396,
  },
  {
    id: '2oFBto8Kxr8',
    title: 'Dhak Dhak Karne Laga',
    film: 'Beta',
    year: 1992,
    singers: 'Anuradha Paudwal Udit Narayan',
    seconds: 306,
  },
  {
    id: 'GwpqME_Cmpc',
    title: 'Aisi Deewangi Dekhi Nahi',
    film: 'Deewana',
    year: 1992,
    singers: 'Vipin Sachdeva Alka Yagnik',
    seconds: 386,
  },
  {
    id: 'tnuwiLr_-nA',
    title: 'Pehla Nasha Pehla Khumar',
    film: 'Jo Jeeta Wohi Sikandar',
    year: 1992,
    singers: 'Udit Narayan Sadhana Sargam',
    seconds: 258,
  },
  {
    id: 'PjiitGT4fUA',
    title: 'Roja Jaaneman',
    film: 'Roja',
    year: 1992,
    singers: 'A R Rahman',
    seconds: 181,
  },
  {
    id: 'E4MxRN2ix88',
    title: 'Dil Hai Chhota Sa',
    film: 'Roja',
    year: 1992,
    singers: 'Minmini',
    seconds: 299,
  },
  {
    id: '-IhD0cSuaqc',
    title: 'Yeh Kaali Kaali Aankhen',
    film: 'Baazigar',
    year: 1993,
    singers: 'Kumar Sanu Anuradha Paudwal',
    seconds: 514,
  },
  {
    id: 'n_oP9Onj0r0',
    title: 'Jaadu Teri Nazar',
    film: 'Darr',
    year: 1993,
    singers: 'Udit Narayan',
    seconds: 158,
  },
  {
    id: 'H5sheEWfsOQ',
    title: 'Ek Ladki Ko Dekha To Aisa Laga',
    film: '1942 A Love Story',
    year: 1994,
    singers: 'Kumar Sanu',
    seconds: 274,
  },
  {
    id: 'ZqcDGvCM_w0',
    title: 'Didi Tera Devar Deewana',
    film: 'Hum Aapke Hain Koun',
    year: 1994,
    singers: 'Lata Mangeshkar Alka Yagnik',
    seconds: 458,
  },
  {
    id: 'fT4vP4PnLxg',
    title: 'Tu Cheez Badi Hai Mast Mast',
    film: 'Mohra',
    year: 1994,
    singers: 'Udit Narayan Kavita Krishnamurthy',
    seconds: 348,
  },
  {
    id: '7JnKVPtRqVE',
    title: 'Tujhe Dekha To Ye Jana Sanam',
    film: 'Dilwale Dulhania Le Jayenge',
    year: 1995,
    singers: 'Kumar Sanu Lata Mangeshkar',
    seconds: 328,
  },
  {
    id: '-bNwqXvMuB8',
    title: 'Mehndi Laga Ke Rakhna',
    film: 'Dilwale Dulhania Le Jayenge',
    year: 1995,
    singers: 'Udit Narayan Lata Mangeshkar',
    seconds: 280,
  },
  {
    id: 'lZ2PhyBF3GQ',
    title: 'Dil To Pagal Hai',
    film: 'Dil To Pagal Hai',
    year: 1997,
    singers: 'Udit Narayan Lata Mangeshkar',
    seconds: 347,
  },
  {
    id: 'K-pX4qwtAxA',
    title: 'Chaiyya Chaiyya',
    film: 'Dil Se',
    year: 1998,
    singers: 'Sukhwinder Singh Sapna Awasthi',
    seconds: 407,
  },
  {
    id: 'bKZTnnFU9HA',
    title: 'Kuch Kuch Hota Hai',
    film: 'Kuch Kuch Hota Hai',
    year: 1998,
    singers: 'Udit Narayan Alka Yagnik',
    seconds: 309,
  },
  {
    id: 'rjtUQAz2KsU',
    title: 'Taal Se Taal Mila',
    film: 'Taal',
    year: 1999,
    singers: 'Alka Yagnik Udit Narayan',
    seconds: 191,
  },
]
